[tool.bumpversion]
current_version = "0.1.3"
parse = "(?P<major>\\d+)\\.(?P<minor>\\d+)\\.(?P<patch>\\d+)"
serialize = ["{major}.{minor}.{patch}"]
search = "{current_version}"
replace = "{new_version}"
regex = false
ignore_missing_version = false
ignore_missing_files = false
tag = true
sign_tags = false
tag_name = "v{new_version}"
tag_message = "Bump version: {current_version} → {new_version}"
allow_dirty = false
commit = true
message = "Bump version: {current_version} → {new_version}"
moveable_tags = []
commit_args = ""
setup_hooks = []
pre_commit_hooks = []
post_commit_hooks = []

[[tool.bumpversion.files]]
filename = "README.md"
search = "version-{current_version}-orange.svg"
replace = "version-{new_version}-orange.svg"

[[tool.bumpversion.files]]
filename = "index.html"
search = "Version <strong>{current_version}</strong>"
replace = "Version <strong>{new_version}</strong>"

[[tool.bumpversion.files]]
filename = "resume/index.html"
search = "Version <strong>{current_version}</strong>"
replace = "Version <strong>{new_version}</strong>"


